### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by NoMaxi** [NoMaxi/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by MaksymNovik** [comment]
Now it is possible to contact you in various ways. Well done!

**Comment by NoMaxi** [comment]
I'll do my best!
